dist: trusty
language: c
compiler: gcc
cache: ccache
addons:
  apt:
    packages:
    - bc
    - ccache
    - device-tree-compiler
script:
  - git config --global user.email "rcnee@example.com"
  - git config --global user.name "rcnee"
  - bash -e build.sh
